---
- name: Our first playbook
  gather_facts: false
  hosts: vagrant
  become: yes
  tasks:
    - name: Display a cool message
      debug:
        msg: "Ansible is working! Hello world! Woooooo!"
    - name: Create a file
      file:
        path: "/home/vagrant/my_file.txt"
        state: touch
    - name: Install the build-essential package
      apt:
        update_cache: yes
        pkg: build-essential
        state: present

- name: Our first playbook
  hosts: vagrant
  become: yes
  vars_files:
    - vars.yml
  roles:
    - geerlingguy.postgresql
  tasks:
    - name: Install postgres CLI tools
      apt:
        update_cache: yes
        pkg: postgresql-client-common
        state: present
