---
- name: Our first playbook
  gather_facts: false
  hosts: vagrant
  tasks:
    - name: Display a cool message
      debug:
        msg: "Ansible is working! Hello world! Woooooo!"
    - name: Create a file
      file:
        path: "/home/vagrant/my_file.txt"
        state: touch
